export interface IFoodItem {
    "Livsmedelsnamn": string;
    "Livsmedelsnummer": number;
    "Gruppering": string;
    "Energi (kcal)": number;
    "Energi (kJ)": number;
    "Fett, totalt (g)": number;
    "Protein (g)": number;
    "Kolhydrater, tillgängliga (g)": number;
    "Fibrer (g)": number;
    "Vatten (g)": number;
    "Alkohol (g)": number;
    "Aska (g)": number;
    "Sockerarter, totalt (g)": number;
    "Monosackarider (g)": number;
    "Disackarider (g)": number;
    "Tillsatt socker (g)": number;
    "Fritt socker (g)": number;
    "Fullkorn totalt (g)": number;
    "Summa mättade fettsyror (g)": string;
    "Fettsyra 4:0-10:0 (g)": number;
    "Laurinsyra C12:0 (g)": string;
    "Myristinsyra C14:0 (g)": string;
    "Palmitinsyra C16:0 (g)": string;
    "Stearinsyra C18:0 (g)": number;
    "Arakidinsyra C20:0 (g)": string;
    "Summa enkelomättade fettsyror (g)": string;
    "Palmitoljesyra C16:1 (g)": number;
    "Oljesyra C18:1 (g)": string;
    "Summa fleromättade fettsyror (g)": string;
    "Linolsyra C18:2 (g)": string;
    "Linolensyra C18:3 (g)": string;
    "Arakidonsyra C20:4 (g)": number;
    "EPA (C20:5) (g)": number;
    "DPA (C22:5) (g)": string;
    "DHA (C22:6) (g)": string;
    "Kolesterol (mg)": number;
    "Vitamin A (RE/µg)": number;
    "Retinol (µg)": number;
    "Betakaroten/β-Karoten (µg)": number;
    "Vitamin D (µg)": number;
    "Vitamin E (mg)": string;
    "Vitamin K (µg)": string;
    "Tiamin (mg)": number;
    "Riboflavin (mg)": number;
    "Niacin (mg)": number;
    "Niacinekvivalenter (NE/mg)": number;
    "Vitamin B6 (mg)": number;
    "Folat (µg)": number;
    "Vitamin B12 (µg)": number;
    "Vitamin C (mg)": number;
    "Fosfor, P (mg)": number;
    "Jod, I (µg)": number;
    "Järn, Fe (mg)": string;
    "Kalcium, Ca (mg)": number;
    "Kalium, K (mg)": number;
    "Magnesium, Mg (mg)": number;
    "Natrium, Na (mg)": number;
    "Salt, NaCl (g)": number;
    "Selen, Se (µg)": number;
    "Zink, Zn (mg)": string;
    "Avfall (skal etc.) (%)": number;

}